// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const awsmobile = {
  aws_project_region: 'eu-central-1',
  aws_cognito_identity_pool_id:
    'eu-central-1:0d4483a9-0874-4069-8244-0660c362f280',
  aws_cognito_region: 'eu-central-1',
  aws_user_pools_id: 'eu-central-1_g9LkAgS5J',
  aws_user_pools_web_client_id: 'p5squm5n23sipdcpvqujjn5cq',
  oauth: {
    domain: 'salonsy907bb107-907bb107-dev.auth.eu-central-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin'
    ],
    redirectSignIn: 'http://localhost:3000/',
    redirectSignOut: 'http://localhost:3000/',
    responseType: 'code'
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_appsync_graphqlEndpoint:
    'https://mqrl7ohyh5eidiaf2g4um4doga.appsync-api.eu-central-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-central-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS'
};
